package com.sproutly.entity;

import jakarta.persistence.*;
import java.time.LocalDate;

/**
 * Entity representing a plant saved by a user.
 *
 * This class is mapped to the "plants" database table and stores:
 * - Basic plant information
 * - Plant photo
 * - Watering schedule
 * - Notes and location
 * - The ID of the user who owns the plant
 */
@Entity
@Table(name = "plants")
public class Plant {

    /**
     * Unique database ID for the plant.
     *
     * The value is automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Name of the plant.
     *
     * This field is required.
     */
    @Column(nullable = false)
    private String name;

    /**
     * Plant photo stored as a large text object.
     *
     * Usually contains a base64 image string or image URL.
     */
    @Lob
    @Column(columnDefinition = "CLOB")
    private String photoUrl;

    /**
     * General plant type.
     *
     * Example:
     * - Indoor
     * - Outdoor
     * - Herb
     */
    private String type;

    /**
     * Optional species identifier or slug.
     */
    private String speciesSlug;

    /**
     * Location where the plant is kept.
     *
     * Example:
     * - Bedroom
     * - Balcony
     * - Kitchen
     */
    private String location;

    /**
     * User notes about the plant.
     */
    private String notes;

    /**
     * Number of days between watering sessions.
     *
     * Default value is 7 days.
     */
    @Column(name = "watering_interval_days")
    private Integer wateringIntervalDays = 7;

    /**
     * Date when the plant was last watered.
     */
    @Column(name = "last_watered")
    private LocalDate lastWatered;

    /**
     * ID of the user who owns the plant.
     *
     * This links the plant to a specific account.
     */
    @Column(name = "user_id", nullable = false)
    private Long userId;

    /**
     * Default constructor required by JPA.
     */
    public Plant() {}

    /**
     * Creates a fully initialized Plant object.
     *
     * @param name plant name
     * @param type plant type
     * @param speciesSlug species identifier
     * @param photoUrl plant photo
     * @param location plant location
     * @param notes user notes
     * @param wateringIntervalDays watering frequency in days
     * @param lastWatered last watering date
     * @param userId owner user ID
     */
    public Plant(String name, String type, String speciesSlug, String photoUrl,
                 String location, String notes, Integer wateringIntervalDays,
                 LocalDate lastWatered, Long userId) {

        this.name = name;
        this.type = type;
        this.speciesSlug = speciesSlug;
        this.photoUrl = photoUrl;
        this.location = location;
        this.notes = notes;
        this.wateringIntervalDays = wateringIntervalDays;
        this.lastWatered = lastWatered;
        this.userId = userId;
    }

    /**
     * Returns the plant ID.
     *
     * @return plant ID
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the plant ID.
     *
     * @param id plant ID
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Returns the plant name.
     *
     * @return plant name
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the plant name.
     *
     * @param name plant name
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Returns the plant type.
     *
     * @return plant type
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the plant type.
     *
     * @param type plant type
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * Returns the species slug.
     *
     * @return species slug
     */
    public String getSpeciesSlug() {
        return speciesSlug;
    }

    /**
     * Sets the species slug.
     *
     * @param speciesSlug species slug
     */
    public void setSpeciesSlug(String speciesSlug) {
        this.speciesSlug = speciesSlug;
    }

    /**
     * Returns the plant photo.
     *
     * @return photo URL or base64 image
     */
    public String getPhotoUrl() {
        return photoUrl;
    }

    /**
     * Sets the plant photo.
     *
     * @param photoUrl photo URL or base64 image
     */
    public void setPhotoUrl(String photoUrl) {
        this.photoUrl = photoUrl;
    }

    /**
     * Returns the plant location.
     *
     * @return location
     */
    public String getLocation() {
        return location;
    }

    /**
     * Sets the plant location.
     *
     * @param location location
     */
    public void setLocation(String location) {
        this.location = location;
    }

    /**
     * Returns user notes about the plant.
     *
     * @return notes
     */
    public String getNotes() {
        return notes;
    }

    /**
     * Sets user notes about the plant.
     *
     * @param notes notes
     */
    public void setNotes(String notes) {
        this.notes = notes;
    }

    /**
     * Returns the watering interval in days.
     *
     * @return watering interval
     */
    public Integer getWateringIntervalDays() {
        return wateringIntervalDays;
    }

    /**
     * Sets the watering interval in days.
     *
     * @param wateringIntervalDays watering interval
     */
    public void setWateringIntervalDays(Integer wateringIntervalDays) {
        this.wateringIntervalDays = wateringIntervalDays;
    }

    /**
     * Returns the last watered date.
     *
     * @return last watered date
     */
    public LocalDate getLastWatered() {
        return lastWatered;
    }

    /**
     * Sets the last watered date.
     *
     * @param lastWatered last watered date
     */
    public void setLastWatered(LocalDate lastWatered) {
        this.lastWatered = lastWatered;
    }

    /**
     * Returns the owner user ID.
     *
     * @return user ID
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * Sets the owner user ID.
     *
     * @param userId user ID
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }
}