package com.sproutly.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;

/**
 * Entity representing an application user.
 *
 * This class is mapped to the "users" database table and stores:
 * - User display name
 * - Email address
 * - Encrypted password
 */
@Entity
@Table(name = "users")
public class User {

    /**
     * Unique database ID for the user.
     *
     * The value is automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Public display name shown in the application.
     *
     * This field cannot be empty.
     */
    @NotBlank
    private String displayName;

    /**
     * User email address.
     *
     * Rules:
     * - Cannot be empty
     * - Must be a valid email format
     * - Must be unique in the database
     */
    @NotBlank
    @Email
    @Column(unique = true)
    private String email;

    /**
     * User password.
     *
     * The password is stored in encrypted form using BCrypt.
     * This field cannot be empty.
     */
    @NotBlank
    private String password;

    /**
     * Default constructor required by JPA.
     */
    public User() {}

    /**
     * Creates a fully initialized User object.
     *
     * @param displayName user's display name
     * @param email user's email address
     * @param password encrypted password
     */
    public User(String displayName, String email, String password) {
        this.displayName = displayName;
        this.email = email;
        this.password = password;
    }

    /**
     * Returns the user ID.
     *
     * @return user ID
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the user ID.
     *
     * @param id user ID
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Returns the user's display name.
     *
     * @return display name
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * Sets the user's display name.
     *
     * @param displayName display name
     */
    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    /**
     * Returns the user's email address.
     *
     * @return email address
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the user's email address.
     *
     * @param email email address
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Returns the encrypted password.
     *
     * @return encrypted password
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the encrypted password.
     *
     * @param password encrypted password
     */
    public void setPassword(String password) {
        this.password = password;
    }
}