spring.datasource.url=jdbc:h2:file:./data/sproutly
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
server.port=8080

plantnet.api.key=2b10oh2pPVHR6l97vvpU7xBHve
trefle.api.token=usr-UnhYia7jYrmBIKVW2G0R5uySCY3-0PjLVyaxYR-wvVQ
perenual.api.key=sk-oPJu6a22b41ab8e3f17965

